### PR TITLE
Add support for hero animations in nested navigators

### PR DESCRIPTION
**Pull request by Eddie-42**
Add support for hero animations (see https://discord.com/channels/1034566655826735135/1065798676682903582)

### CODE REVIEW

**Comment by fynsta** [comment]
Simon and I have argued about whether this looks good (better than no animation?):

https://user-images.githubusercontent.com/63241108/213893415-efdd66c5-0125-46b4-a4c2-4274b7f97b3d.mov

We agree on all the other heros, but not on the FloatingActionButton ones that open a whole page.

**Comment by Showcas** [comment]
> Simon and I have argued about whether this looks good (better than no animation?):
> 
>  Screen.Recording.2023-01-21.at.22.20.48.mov 
> We agree on all the other heros, but not on the FloatingActionButton ones that open a whole page.

I think the blue screen in between looks like a bug

**Comment by istzen** [comment]
the diff is broken isn't it?

**Comment by fynsta** [comment]
Oh no, how did that happen? The PR is literally just a one-line change :D

**Comment by istzen** [comment]
> Oh no, how did that happen? The PR is literally just a one-line change :D

yes i thought so too xD

**Comment by fynsta** [comment]
Okay fixed the diff... No idea how that got so messed up though

**Review by istzen — APPROVED** [review]

**Review by Showcas — APPROVED** [review]

**Comment by fynsta** [comment]
@Eddie-42 the others seem to agree with me, so I'll remove the Fab Heros for now.

**Review by fynsta — APPROVED** [review]

**Review by MarkFalke — APPROVED** [review]

**Comment by Eddie-42** [comment]
> > Simon and I have argued about whether this looks good (better than no animation?):
> > Screen.Recording.2023-01-21.at.22.20.48.mov
> > We agree on all the other heros, but not on the FloatingActionButton ones that open a whole page.
> 
> I think the blue screen in between looks like a bug



> @Eddie-42 the others seem to agree with me, so I'll remove the Fab Heros for now.

Due to popular demand, I have fixed the blue flashing and heros are up and running again

**Pull request merged**
